# To run this bot, comment "@bot /style" on a PR
name: Style Bot

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  style:
    # change back to `@style_notify` once https://github.com/huggingface/huggingface_hub/pull/3179 is merged
    uses: huggingface/huggingface_hub/.github/workflows/style-bot-action.yml@style_notify
    with:
      python_quality_dependencies: "[quality]"
      style_command_type: "default"
    secrets:
      bot_token: ${{ secrets.HF_STYLE_BOT_ACTION }}
